spring:
  application:
    name: ms-products

#APACHE
server:
  port: 8181

#REFRESH_SCOPE CONFIG
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

#EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true